# Generated by Django 5.2.16 on 2026-07-26 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF file uploaded by the user.', upload_to='uploads/')),
                ('original_name', models.CharField(help_text='Original filename before renaming.', max_length=255)),
                ('tipo_equipo', models.CharField(blank=True, default='', max_length=100)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('codigo_interno', models.CharField(blank=True, default='', max_length=100)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_mantenimiento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('indexed', 'Indexado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
