# Generated by Django 5.2.16 on 2026-07-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Archivo PDF cargado por el usuario.', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_name',
            field=models.CharField(help_text='Nombre original del archivo antes de renombrarlo.', max_length=255),
        ),
    ]
